# Generated by Django 5.2.15 on 2026-06-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='Hackathon', max_length=50),
            preserve_default=False,
        ),
    ]
