# Generated by Django 5.2.15 on 2026-06-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='seats_available',
            field=models.IntegerField(default=50),
        ),
    ]
