# Generated by Django 5.2.15 on 2026-06-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_registration_seats_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='seats_available',
        ),
        migrations.AddField(
            model_name='event',
            name='seats_available',
            field=models.IntegerField(default=50),
        ),
    ]
