# Generated by Django 5.2.15 on 2026-06-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_registration_seats_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='seats_available',
            new_name='total_slots',
        ),
    ]
